# Generated by Django 6.1.1 on 2026-10-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('otp_id', models.AutoField(primary_key=True, serialize=False)),
                ('otp_code_hash', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('LOGIN', 'Login'), ('TRANSFER', 'Transfer'), ('BILL_PAYMENT', 'Bill Payment'), ('PROFILE_UPDATE', 'Profile Update')], max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'otp_verifications',
            },
        ),
    ]
