# Generated by Django 6.0.9 on 2026-10-08 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDriftMetric',
            fields=[
                ('metric_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('feature_name', models.CharField(max_length=100)),
                ('psi_score', models.FloatField(help_text='Population Stability Index')),
                ('is_drifted', models.BooleanField(default=False)),
                ('baseline_mean', models.FloatField(blank=True, null=True)),
                ('current_mean', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ml_data_drift_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('version_id', models.AutoField(primary_key=True, serialize=False)),
                ('version_tag', models.CharField(max_length=100, unique=True)),
                ('model_type', models.CharField(default='XGBoost', max_length=50)),
                ('roc_auc', models.FloatField(blank=True, null=True)),
                ('auprc', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('training_samples', models.IntegerField(blank=True, null=True)),
                ('fraud_samples', models.IntegerField(blank=True, null=True)),
                ('training_duration_sec', models.FloatField(blank=True, null=True)),
                ('dataset_hash', models.CharField(blank=True, max_length=64)),
                ('model_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('TRAINING', 'Training'), ('CANDIDATE', 'Candidate'), ('VALIDATED', 'Validated'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('FAILED', 'Failed'), ('ROLLED_BACK', 'Rolled Back')], default='TRAINING', max_length=20)),
                ('training_log', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('replaced_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trained_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_model_versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetrainingJob',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('celery_task_id', models.CharField(blank=True, max_length=100)),
                ('trigger', models.CharField(choices=[('MANUAL', 'Manual'), ('SCHEDULED', 'Scheduled'), ('DRIFT', 'Drift Detected'), ('DEGRADATION', 'Performance Drop')], default='MANUAL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_sec', models.FloatField(blank=True, null=True)),
                ('log_output', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retraining_jobs', to='ml_pipeline.modelversion')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_retraining_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelPerformanceLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('predictions_count', models.IntegerField(default=0)),
                ('flagged_count', models.IntegerField(default=0)),
                ('confirmed_fraud', models.IntegerField(default=0)),
                ('false_positive', models.IntegerField(default=0)),
                ('avg_fraud_score', models.FloatField(blank=True, null=True)),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_logs', to='ml_pipeline.modelversion')),
            ],
            options={
                'db_table': 'ml_performance_logs',
                'ordering': ['-date'],
                'unique_together': {('model_version', 'date')},
            },
        ),
    ]
