# Generated by Django 6.1.1 on 2026-10-02 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('reference_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('TRANSFER', 'Transfer'), ('BILL_PAYMENT', 'Bill Payment'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('LOAN_PAYMENT', 'Loan Payment'), ('RECHARGE', 'Mobile Recharge')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed'), ('HELD', 'Held for Review')], default='PENDING', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('otp_verified', models.BooleanField(default=False)),
                ('fraud_score', models.FloatField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beneficiaries.beneficiary')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='outgoing_transactions', to='accounts.account')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='incoming_transactions', to='accounts.account')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['from_account', 'created_at'], name='transaction_from_ac_68109f_idx'), models.Index(fields=['status'], name='transaction_status_505a2f_idx')],
            },
        ),
    ]
