# Generated by Django 6.1.1 on 2026-10-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fraud_explanation',
            field=models.JSONField(blank=True, help_text='SHAP feature contributions', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='risk_level',
            field=models.CharField(blank=True, help_text='SAFE/LOW/MEDIUM/HIGH', max_length=10),
        ),
    ]
