# Generated by Django 6.1.1 on 2026-10-03 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('kyc_id', models.AutoField(primary_key=True, serialize=False)),
                ('nid_number', models.CharField(max_length=50, unique=True)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('document_type', models.CharField(default='NID', max_length=50)),
                ('document_front', models.ImageField(blank=True, null=True, upload_to='kyc/')),
                ('document_back', models.ImageField(blank=True, null=True, upload_to='kyc/')),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='kyc/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_kycs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kyc',
                'ordering': ['-created_at'],
            },
        ),
    ]
